### ISSUE TITLE
Is the document outdated ?

### ISSUE THREAD

**Issue by tridungpham** [vafour/vafpress-framework#5] opened 2013-08-05 10:47 UTC
Hi , I'm totally impressed with your demo and wanna use the framework in my theme. I followed your document, that tell me add the line 

``` php
require_once 'vafpress-framework/bootstrap.php';
```

in my theme's functions.php file. But after adding that line, nothing happened. No "Theme Options" submenu under Appearance in Dashboard. ( the bootstrap.php file included, but seems to do nothing ?).

And, is the document outdated or I miss some steps ? For example, it tells me to open 

``` php
\vafpress\core\config\option.php
```

but I cannot find the "core" directory.

**Comment by daviedR** [comment] 2013-08-05 12:11
Hi, yes.. Our current documentation refers to the legacy version which is tagged as version 1.2 in our github repository 
(https://github.com/vafour/vafpress-framework/releases/tag/v1.2_legacy). You might have downloaded and installed the current changeset, which hasn't been officially released, since we still make enhancement in many parts, including rewrite our documentation.

So for the time being, sorry that we still couldn't push the new documentation online. But we will do it soon. Anyway, If you really want to try out the new version, we have make separate repository named, "Vafpress Framework Theme Boilerplate" (https://github.com/vafour/vafpress-framework-theme-boilerplate). This repository is supposed to be a live example about how to use the new vafpress framework on a theme. There you can download and place it into the WP theme directory, you can see how we initialize options page and metaboxes in the functions.php. But again, this is not officially released yet.

Sorry for this inconvenience,

Regards

**Comment by tridungpham** [comment] 2013-08-06 07:03
Hi DaviedR, thank you for your reply.
I'm testing the boilerplate theme. Everything seems to be fine.
But I set WP_DEBUG to true, I notice that there're many strict standards errors. For example, I have to add "static" to some methods in WPAlchemy_MetaBox class , to suppress the "non-static method can not be called statically" error.

**Comment by ayublin** [comment] 2013-08-07 14:04
Hi, how can we reproduce those notices? can you paste or capture them here? I tried adding:

```
error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', 1);
define('WP_DEBUG', true);
```

In wp-config.php file and no notices appeared, and I am running PHP 5.2.9 here.

Thanks.

**Comment by tridungpham** [comment] 2013-08-08 04:19
I assume that you should use a higher version of PHP. I'm running 5.4.9 in my dev machine.
You can see the error here https://app.box.com/files/0/f/1070404249/1/f_9651911827 
The errors seems come from WPAlchemy_Metabox class.

**Comment by ayublin** [comment] 2013-08-12 05:52
Hi, I just tried using PHP 5.5.1 but still no error messages appeared, and can you please make sure that your link to the screenshot is public? I can't access it here.

Thanks!

**Comment by tridungpham** [comment] 2013-08-12 09:21
Oops, my mistake, I posted the wrong link . Please try this link : https://app.box.com/s/9tfrv645ub2omj635f04

**Comment by ayublin** [comment] 2013-08-12 11:46
Oh wow, you're right, those warnings come from WPAlchemy class, thanks for the screenshot we should be able to fix them with that, but can you explain how could you make PHP showed those warning in such detailed way? since I can't even managed to shows any warning even with the latest XAMPP here.

**Comment by tridungpham** [comment] 2013-08-13 02:18
I run PHP 5.4.9 , and set 

```
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
```

in my php.ini. Is that helpful ?

**Comment by ayublin** [comment] 2013-08-13 04:20
Hmm, weird, still no success, are you not using any kind of extensions?

But we have updated the framework based on the warnings that you provided, if you can confirm the warnings are gone now, that would be awesome :smile:

**Comment by tridungpham** [comment] 2013-08-13 05:07
I've just tried the updated boilerplate theme. Seems to be good so far. But there're still some strict standard warnings. You can see it here http://pastebin.com/wbNRRQX1
The log's contains some notice from other plugins. Just ignore it :smile:

if I turn off WP_DEBUG, the framework is ok. Btw, I use developer (http://wordpress.org/plugins/developer/) plugin to install some other plugins :
![debug plugins](http://i.imgur.com/VM9Z8EL.png)

**Comment by ayublin** [comment] 2013-08-13 07:41
Oh wow, I really need to enable the notices on my own machine then, can I see the content of your phpinfo? I figured out that you're using xdebug PHP extension, I installed it but still unable to shows strict standards.

**Comment by tridungpham** [comment] 2013-08-13 08:17
Wow, funny problem :smile: ? Here is phpinfo() ouput https://app.box.com/s/c8tyu2djwlv9vbkc9vnp

**Comment by ayublin** [comment] 2013-08-14 06:05
Hi Tridungpham, I finally figured out why the notices weren't appearing, somehow WP with version less than 3.6 disable the E_STRICT error reporting level, so now we can begin to fix those notices, will notify you here once we done fixing those, thanks :)

**Comment by ayublin** [comment] 2013-08-14 10:14
Notices seems to be fixed now, please confirm, thanks :)

**Closed as completed** 2013-08-16 05:19 UTC

**Comment by ayublin** [comment] 2013-08-23 10:41
Hi tridungpham. Just want to give a heads up, we have just updated our documentation :)

**Comment by tridungpham** [comment] 2013-08-25 17:28
Hi ayublin, thank you for your hard work :) . Somehow I muted this thread so I didn't receive any notifications :( . I've just checked the updated document. Well done :+1:

**Comment by ayublin** [comment] 2013-08-28 09:07
Ahh I see, and thanks for the kind words! :smile:
